spring:
  application:
    name: collection
  datasource:
    url: 'jdbc:postgresql://localhost/collection'
    username: postgres
    password: postgres1
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    url: 'jdbc:postgresql://localhost/collection'
    user: postgres
    password: postgres1
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
  servlet:
    multipart:
      enabled: true
logging:
  level:
    root: info