name: Unit Tests
on: [push, pull-request]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Tests
        run: |
          ./gradlew test
